var map = [
  { pattern: "滑", target: "滑", enable: true },
  { pattern: "串", target: "串", enable: true },
  { pattern: "句", target: "句", enable: true },
  { pattern: "契", target: "契", enable: true },
  { pattern: "金", target: "金", enable: true },
  { pattern: "喇", target: "喇", enable: true },
  { pattern: "奈", target: "奈", enable: true },
  { pattern: "螺", target: "螺", enable: true },
  { pattern: "裸", target: "裸", enable: true },
  { pattern: "洛", target: "洛", enable: true },
  { pattern: "烙", target: "烙", enable: true },
  { pattern: "落", target: "落", enable: true },
  { pattern: "酪", target: "酪", enable: true },
  { pattern: "卵", target: "卵", enable: true },
  { pattern: "拉", target: "拉", enable: true },
  { pattern: "廊", target: "廊", enable: true },
  { pattern: "浪", target: "浪", enable: true },
  { pattern: "狼", target: "狼", enable: true },
  { pattern: "老", target: "老", enable: true },
  { pattern: "路", target: "路", enable: true },
  { pattern: "露", target: "露", enable: true },
  { pattern: "鹿", target: "鹿", enable: true },
  { pattern: "弄", target: "弄", enable: true },
  { pattern: "牢", target: "牢", enable: true },
  { pattern: "磊", target: "磊", enable: true },
  { pattern: "雷", target: "雷", enable: true },
  { pattern: "漏", target: "漏", enable: true },
  { pattern: "陋", target: "陋", enable: true },
  { pattern: "勒", target: "勒", enable: true },
  { pattern: "肋", target: "肋", enable: true },
  { pattern: "凌", target: "凌", enable: true },
  { pattern: "陵", target: "陵", enable: true },
  { pattern: "丹", target: "丹", enable: true },
  { pattern: "怒", target: "怒", enable: true },
  { pattern: "率", target: "率", enable: true },
  { pattern: "北", target: "北", enable: true },
  { pattern: "便", target: "便", enable: true },
  { pattern: "不", target: "不", enable: true },
  { pattern: "泌", target: "泌", enable: true },
  { pattern: "塞", target: "塞", enable: true },
  { pattern: "省", target: "省", enable: true },
  { pattern: "辰", target: "辰", enable: true },
  { pattern: "沈", target: "沈", enable: true },
  { pattern: "拾", target: "拾", enable: true },
  { pattern: "若", target: "若", enable: true },
  { pattern: "掠", target: "掠", enable: true },
  { pattern: "略", target: "略", enable: true },
  { pattern: "亮", target: "亮", enable: true },
  { pattern: "凉", target: "凉", enable: true },
  { pattern: "梁", target: "梁", enable: true },
  { pattern: "良", target: "良", enable: true },
  { pattern: "量", target: "量", enable: true },
  { pattern: "女", target: "女", enable: true },
  { pattern: "旅", target: "旅", enable: true },
  { pattern: "黎", target: "黎", enable: true },
  { pattern: "力", target: "力", enable: true },
  { pattern: "念", target: "年", enable: true },
  { pattern: "列", target: "列", enable: true },
  { pattern: "劣", target: "劣", enable: true },
  { pattern: "咽", target: "咽", enable: true },
  { pattern: "烈", target: "烈", enable: true },
  { pattern: "裂", target: "裂", enable: true },
  { pattern: "例", target: "例", enable: true },
  { pattern: "了", target: "了", enable: true },
  { pattern: "僚", target: "僚", enable: true },
  { pattern: "寮", target: "寮", enable: true },
  { pattern: "尿", target: "尿", enable: true },
  { pattern: "料", target: "料", enable: true },
  { pattern: "燎", target: "燎", enable: true },
  { pattern: "柳", target: "柳", enable: true },
  { pattern: "流", target: "流", enable: true },
  { pattern: "溜", target: "溜", enable: true },
  { pattern: "琉", target: "琉", enable: true },
  { pattern: "留", target: "留", enable: true },
  { pattern: "硫", target: "硫", enable: true },
  { pattern: "六", target: "六", enable: true },
  { pattern: "律", target: "律", enable: true },
  { pattern: "栗", target: "栗", enable: true },
  { pattern: "率", target: "率", enable: true },
  { pattern: "隆", target: "隆", enable: true },
  { pattern: "利", target: "利", enable: true },
  { pattern: "吏", target: "吏", enable: true },
  { pattern: "履", target: "履", enable: true },
  { pattern: "易", target: "易", enable: true },
  { pattern: "李", target: "李", enable: true },
  { pattern: "梨", target: "梨", enable: true },
  { pattern: "泥", target: "泥", enable: true },
  { pattern: "理", target: "理", enable: true },
  { pattern: "痢", target: "痢", enable: true },
  { pattern: "罹", target: "罹", enable: true },
  { pattern: "里", target: "里", enable: true },
  { pattern: "匿", target: "匿", enable: true },
  { pattern: "吝", target: "吝", enable: true },
  { pattern: "林", target: "林", enable: true },
  { pattern: "淋", target: "淋", enable: true },
  { pattern: "立", target: "立", enable: true },
  { pattern: "笠", target: "笠", enable: true },
  { pattern: "粒", target: "粒", enable: true },
  { pattern: "炙", target: "炙", enable: true },
  { pattern: "什", target: "什", enable: true },
  { pattern: "刺", target: "刺", enable: true },
  { pattern: "度", target: "度", enable: true },
  { pattern: "拓", target: "拓", enable: true },
  { pattern: "糖", target: "糖", enable: true },
  { pattern: "宅", target: "宅", enable: true },
  { pattern: "洞", target: "洞", enable: true },
  { pattern: "暴", target: "暴", enable: true },
  { pattern: "行", target: "行", enable: true },
  { pattern: "廓", target: "廓", enable: true },
  { pattern: "兀", target: "兀", enable: true },
  { pattern: "逸", target: "逸", enable: true },
  { pattern: "勉", target: "勉", enable: true },
  { pattern: "勤", target: "勤", enable: true },
  { pattern: "卑", target: "卑", enable: true },
  { pattern: "喝", target: "喝", enable: true },
  { pattern: "器", target: "器", enable: true },
  { pattern: "墨", target: "墨", enable: true },
  { pattern: "悔", target: "悔", enable: true },
  { pattern: "敏", target: "敏", enable: true },
  { pattern: "梅", target: "梅", enable: true },
  { pattern: "海", target: "海", enable: true },
  { pattern: "琢", target: "琢", enable: true },
  { pattern: "碑", target: "碑", enable: true },
  { pattern: "臭", target: "臭", enable: true },
  { pattern: "褐", target: "褐", enable: true },
];
var $exec = document.getElementById("exec");
$exec.onclick = () => {
  var raw = document.getElementById("raw").value;
  map.forEach((e) => {
    if (e.enable) {
      raw = raw.replaceAll(e.pattern, "<cd>" + e.target + "</cd>");
    }
  });
  document.getElementById("edited").innerHTML = raw;
};
var patt = "";
var cnt=0;
map.forEach((e) => {
  if (e.enable) {
    patt += e.pattern+"→"+e.target+" ";
    ++cnt;
    if(cnt%21==0){
        patt+='<br>'
    }
  }
});
document.getElementById("pattern").innerHTML = patt;
